l=[]
a=input("Enter your name:")
l.append(a)
a=int(input("Enter your age:"))
l.append(a)
a=input("Enter your gender:")
l.append(a)
a=input("Enter your occupation:")
l.append(a)
a=input("Enter your address:")
l.append(a)
a=int(input("Enter your phone number:"))
l.append(a)
a=input("Enter your mother's name:")
l.append(a)
a=input("Enter your father's name:")
l.append(a)
a=input("Enter your number of siblings:")
l.append(a)
print("The details which you entered are as follows:")
for i in l:
    print (i)
